name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      uses: actions/python-actions@v2
      with:
        python-version: 3.10
        script: ds9crop.py
